<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="data:text/css;charset=utf-8,%0A%40font%2Dface%20%7B%0Afont%2Dfamily%3A%20octicons%2Dlink%3B%0Asrc%3A%20url%28data%3Afont%2Fwoff%3Bcharset%3Dutf%2D8%3Bbase64%2Cd09GRgABAAAAAAZwABAAAAAACFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEU0lHAAAGaAAAAAgAAAAIAAAAAUdTVUIAAAZcAAAACgAAAAoAAQAAT1MvMgAAAyQAAABJAAAAYFYEU3RjbWFwAAADcAAAAEUAAACAAJThvmN2dCAAAATkAAAABAAAAAQAAAAAZnBnbQAAA7gAAACyAAABCUM%2B8IhnYXNwAAAGTAAAABAAAAAQABoAI2dseWYAAAFsAAABPAAAAZwcEq9taGVhZAAAAsgAAAA0AAAANgh4a91oaGVhAAADCAAAABoAAAAkCA8DRGhtdHgAAAL8AAAADAAAAAwGAACfbG9jYQAAAsAAAAAIAAAACABiATBtYXhwAAACqAAAABgAAAAgAA8ASm5hbWUAAAToAAABQgAAAlXu73sOcG9zdAAABiwAAAAeAAAAME3QpOBwcmVwAAAEbAAAAHYAAAB%2FaFGpk3jaTY6xa8JAGMW%2FO62BDi0tJLYQincXEypYIiGJjSgHniQ6umTsUEyLm5BV6NDBP8Tpts6F0v%2Bk%2F0an2i%2BitHDw3v2%2B9%2BDBKTzsJNnWJNTgHEy4BgG3EMI9DCEDOGEXzDADU5hBKMIgNPZqoD3SilVaXZCER3%2FI7AtxEJLtzzuZfI%2BVVkprxTlXShWKb3TBecG11rwoNlmmn1P2WYcJczl32etSpKnziC7lQyWe1smVPy%2FLt7Kc%2B0vWY%2FgAgIIEqAN9we0pwKXreiMasxvabDQMM4riO%2BqxM2ogwDGOZTXxwxDiycQIcoYFBLj5K3EIaSctAq2kTYiw%2Bymhce7vwM9jSqO8JyVd5RH9gyTt2%2BJ%2FyUmYlIR0s04n6%2B7Vm1ozezUeLEaUjhaDSuXHwVRgvLJn1tQ7xiuVv%2FocTRF42mNgZGBgYGbwZOBiAAFGJBIMAAizAFoAAABiAGIAznjaY2BkYGAA4in8zwXi%2BW2%2BMjCzMIDApSwvXzC97Z4Ig8N%2FBxYGZgcgl52BCSQKAA3jCV8CAABfAAAAAAQAAEB42mNgZGBg4f3vACQZQABIMjKgAmYAKEgBXgAAeNpjYGY6wTiBgZWBg2kmUxoDA4MPhGZMYzBi1AHygVLYQUCaawqDA4PChxhmh%2F8ODDEsvAwHgMKMIDnGL0x7gJQCAwMAJd4MFwAAAHjaY2BgYGaA4DAGRgYQkAHyGMF8NgYrIM3JIAGVYYDT%2BAEjAwuDFpBmA9KMDEwMCh9i%2Fv8H8sH0%2F4dQc1iAmAkALaUKLgAAAHjaTY9LDsIgEIbtgqHUPpDi3gPoBVyRTmTddOmqTXThEXqrob2gQ1FjwpDvfwCBdmdXC5AVKFu3e5MfNFJ29KTQT48Ob9%2FlqYwOGZxeUelN2U2R6%2BcArgtCJpauW7UQBqnFkUsjAY%2FkOU1cP%2BDAgvxwn1chZDwUbd6CFimGXwzwF6tPbFIcjEl%2BvvmM%2FbyA48e6tWrKArm4ZJlCbdsrxksL1AwWn%2FyBSJKpYbq8AXaaTb8AAHja28jAwOC00ZrBeQNDQOWO%2F%2FsdBBgYGRiYWYAEELEwMTE4uzo5Zzo5b2BxdnFOcALxNjA6b2ByTswC8jYwg0VlNuoCTWAMqNzMzsoK1rEhNqByEyerg5PMJlYuVueETKcd%2F89uBpnpvIEVomeHLoMsAAe1Id4AAAAAAAB42oWQT07CQBTGv0JBhagk7HQzKxca2sJCE1hDt4QF%2B9JOS0nbaaYDCQfwCJ7Au3AHj%2BLO13FMmm6cl7785vven0kBjHCBhfpYuNa5Ph1c0e2Xu3jEvWG7UdPDLZ4N92nOm%2BEBXuAbHmIMSRMs%2B4aUEd4Nd3CHD8NdvOLTsA2GL8M9PODbcL%2BhD7C1xoaHeLJSEao0FEW14ckxC%2BTU8TxvsY6X0eLPmRhry2WVioLpkrbp84LLQPGI7c6sOiUzpWIWS5GzlSgUzzLBSikOPFTOXqly7rqx0Z1Q5BAIoZBSFihQYQOOBEdkCOgXTOHA07HAGjGWiIjaPZNW13%2F%2Blm6S9FT7rLHFJ6fQbkATOG1j2OFMucKJJsxIVfQORl%2B9Jyda6Sl1dUYhSCm1dyClfoeDve4qMYdLEbfqHf3O%2FAdDumsjAAB42mNgYoAAZQYjBmyAGYQZmdhL8zLdDEydARfoAqIAAAABAAMABwAKABMAB%2F%2F%2FAA8AAQAAAAAAAAAAAAAAAAABAAAAAA%3D%3D%29%20format%28%27woff%27%29%3B%0A%7D%0Abody%20%7B%0A%2Dwebkit%2Dtext%2Dsize%2Dadjust%3A%20100%25%3B%0Atext%2Dsize%2Dadjust%3A%20100%25%3B%0Acolor%3A%20%23333%3B%0Afont%2Dfamily%3A%20%22Helvetica%20Neue%22%2C%20Helvetica%2C%20%22Segoe%20UI%22%2C%20Arial%2C%20freesans%2C%20sans%2Dserif%2C%20%22Apple%20Color%20Emoji%22%2C%20%22Segoe%20UI%20Emoji%22%2C%20%22Segoe%20UI%20Symbol%22%3B%0Afont%2Dsize%3A%2016px%3B%0Aline%2Dheight%3A%201%2E6%3B%0Aword%2Dwrap%3A%20break%2Dword%3B%0A%7D%0Aa%20%7B%0Abackground%2Dcolor%3A%20transparent%3B%0A%7D%0Aa%3Aactive%2C%0Aa%3Ahover%20%7B%0Aoutline%3A%200%3B%0A%7D%0Astrong%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Ah1%20%7B%0Afont%2Dsize%3A%202em%3B%0Amargin%3A%200%2E67em%200%3B%0A%7D%0Aimg%20%7B%0Aborder%3A%200%3B%0A%7D%0Ahr%20%7B%0Abox%2Dsizing%3A%20content%2Dbox%3B%0Aheight%3A%200%3B%0A%7D%0Apre%20%7B%0Aoverflow%3A%20auto%3B%0A%7D%0Acode%2C%0Akbd%2C%0Apre%20%7B%0Afont%2Dfamily%3A%20monospace%2C%20monospace%3B%0Afont%2Dsize%3A%201em%3B%0A%7D%0Ainput%20%7B%0Acolor%3A%20inherit%3B%0Afont%3A%20inherit%3B%0Amargin%3A%200%3B%0A%7D%0Ahtml%20input%5Bdisabled%5D%20%7B%0Acursor%3A%20default%3B%0A%7D%0Ainput%20%7B%0Aline%2Dheight%3A%20normal%3B%0A%7D%0Ainput%5Btype%3D%22checkbox%22%5D%20%7B%0Abox%2Dsizing%3A%20border%2Dbox%3B%0Apadding%3A%200%3B%0A%7D%0Atable%20%7B%0Aborder%2Dcollapse%3A%20collapse%3B%0Aborder%2Dspacing%3A%200%3B%0A%7D%0Atd%2C%0Ath%20%7B%0Apadding%3A%200%3B%0A%7D%0A%2A%20%7B%0Abox%2Dsizing%3A%20border%2Dbox%3B%0A%7D%0Ainput%20%7B%0Afont%3A%2013px%20%2F%201%2E4%20Helvetica%2C%20arial%2C%20nimbussansl%2C%20liberationsans%2C%20freesans%2C%20clean%2C%20sans%2Dserif%2C%20%22Apple%20Color%20Emoji%22%2C%20%22Segoe%20UI%20Emoji%22%2C%20%22Segoe%20UI%20Symbol%22%3B%0A%7D%0Aa%20%7B%0Acolor%3A%20%234078c0%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Aa%3Ahover%2C%0Aa%3Aactive%20%7B%0Atext%2Ddecoration%3A%20underline%3B%0A%7D%0Ahr%20%7B%0Aheight%3A%200%3B%0Amargin%3A%2015px%200%3B%0Aoverflow%3A%20hidden%3B%0Abackground%3A%20transparent%3B%0Aborder%3A%200%3B%0Aborder%2Dbottom%3A%201px%20solid%20%23ddd%3B%0A%7D%0Ahr%3Abefore%20%7B%0Adisplay%3A%20table%3B%0Acontent%3A%20%22%22%3B%0A%7D%0Ahr%3Aafter%20%7B%0Adisplay%3A%20table%3B%0Aclear%3A%20both%3B%0Acontent%3A%20%22%22%3B%0A%7D%0Ah1%2C%0Ah2%2C%0Ah3%2C%0Ah4%2C%0Ah5%2C%0Ah6%20%7B%0Amargin%2Dtop%3A%2015px%3B%0Amargin%2Dbottom%3A%2015px%3B%0Aline%2Dheight%3A%201%2E1%3B%0A%7D%0Ah1%20%7B%0Afont%2Dsize%3A%2030px%3B%0A%7D%0Ah2%20%7B%0Afont%2Dsize%3A%2021px%3B%0A%7D%0Ah3%20%7B%0Afont%2Dsize%3A%2016px%3B%0A%7D%0Ah4%20%7B%0Afont%2Dsize%3A%2014px%3B%0A%7D%0Ah5%20%7B%0Afont%2Dsize%3A%2012px%3B%0A%7D%0Ah6%20%7B%0Afont%2Dsize%3A%2011px%3B%0A%7D%0Ablockquote%20%7B%0Amargin%3A%200%3B%0A%7D%0Aul%2C%0Aol%20%7B%0Apadding%3A%200%3B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Aol%20ol%2C%0Aul%20ol%20%7B%0Alist%2Dstyle%2Dtype%3A%20lower%2Droman%3B%0A%7D%0Aul%20ul%20ol%2C%0Aul%20ol%20ol%2C%0Aol%20ul%20ol%2C%0Aol%20ol%20ol%20%7B%0Alist%2Dstyle%2Dtype%3A%20lower%2Dalpha%3B%0A%7D%0Add%20%7B%0Amargin%2Dleft%3A%200%3B%0A%7D%0Acode%20%7B%0Afont%2Dfamily%3A%20Consolas%2C%20%22Liberation%20Mono%22%2C%20Menlo%2C%20Courier%2C%20monospace%3B%0Afont%2Dsize%3A%2012px%3B%0A%7D%0Apre%20%7B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%200%3B%0Afont%3A%2012px%20Consolas%2C%20%22Liberation%20Mono%22%2C%20Menlo%2C%20Courier%2C%20monospace%3B%0A%7D%0A%2Eselect%3A%3A%2Dms%2Dexpand%20%7B%0Aopacity%3A%200%3B%0A%7D%0A%2Eocticon%20%7B%0Afont%3A%20normal%20normal%20normal%2016px%2F1%20octicons%2Dlink%3B%0Adisplay%3A%20inline%2Dblock%3B%0Atext%2Ddecoration%3A%20none%3B%0Atext%2Drendering%3A%20auto%3B%0A%2Dwebkit%2Dfont%2Dsmoothing%3A%20antialiased%3B%0A%2Dmoz%2Dosx%2Dfont%2Dsmoothing%3A%20grayscale%3B%0A%2Dwebkit%2Duser%2Dselect%3A%20none%3B%0A%2Dmoz%2Duser%2Dselect%3A%20none%3B%0A%2Dms%2Duser%2Dselect%3A%20none%3B%0Auser%2Dselect%3A%20none%3B%0A%7D%0A%2Eocticon%2Dlink%3Abefore%20%7B%0Acontent%3A%20%27%5Cf05c%27%3B%0A%7D%0A%2Emarkdown%2Dbody%3Abefore%20%7B%0Adisplay%3A%20table%3B%0Acontent%3A%20%22%22%3B%0A%7D%0A%2Emarkdown%2Dbody%3Aafter%20%7B%0Adisplay%3A%20table%3B%0Aclear%3A%20both%3B%0Acontent%3A%20%22%22%3B%0A%7D%0A%2Emarkdown%2Dbody%3E%2A%3Afirst%2Dchild%20%7B%0Amargin%2Dtop%3A%200%20%21important%3B%0A%7D%0A%2Emarkdown%2Dbody%3E%2A%3Alast%2Dchild%20%7B%0Amargin%2Dbottom%3A%200%20%21important%3B%0A%7D%0Aa%3Anot%28%5Bhref%5D%29%20%7B%0Acolor%3A%20inherit%3B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0A%2Eanchor%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0Apadding%2Dright%3A%202px%3B%0Amargin%2Dleft%3A%20%2D18px%3B%0A%7D%0A%2Eanchor%3Afocus%20%7B%0Aoutline%3A%20none%3B%0A%7D%0Ah1%2C%0Ah2%2C%0Ah3%2C%0Ah4%2C%0Ah5%2C%0Ah6%20%7B%0Amargin%2Dtop%3A%201em%3B%0Amargin%2Dbottom%3A%2016px%3B%0Afont%2Dweight%3A%20bold%3B%0Aline%2Dheight%3A%201%2E4%3B%0A%7D%0Ah1%20%2Eocticon%2Dlink%2C%0Ah2%20%2Eocticon%2Dlink%2C%0Ah3%20%2Eocticon%2Dlink%2C%0Ah4%20%2Eocticon%2Dlink%2C%0Ah5%20%2Eocticon%2Dlink%2C%0Ah6%20%2Eocticon%2Dlink%20%7B%0Acolor%3A%20%23000%3B%0Avertical%2Dalign%3A%20middle%3B%0Avisibility%3A%20hidden%3B%0A%7D%0Ah1%3Ahover%20%2Eanchor%2C%0Ah2%3Ahover%20%2Eanchor%2C%0Ah3%3Ahover%20%2Eanchor%2C%0Ah4%3Ahover%20%2Eanchor%2C%0Ah5%3Ahover%20%2Eanchor%2C%0Ah6%3Ahover%20%2Eanchor%20%7B%0Atext%2Ddecoration%3A%20none%3B%0A%7D%0Ah1%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah2%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah3%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah4%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah5%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%2C%0Ah6%3Ahover%20%2Eanchor%20%2Eocticon%2Dlink%20%7B%0Avisibility%3A%20visible%3B%0A%7D%0Ah1%20%7B%0Apadding%2Dbottom%3A%200%2E3em%3B%0Afont%2Dsize%3A%202%2E25em%3B%0Aline%2Dheight%3A%201%2E2%3B%0Aborder%2Dbottom%3A%201px%20solid%20%23eee%3B%0A%7D%0Ah1%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%3B%0A%7D%0Ah2%20%7B%0Apadding%2Dbottom%3A%200%2E3em%3B%0Afont%2Dsize%3A%201%2E75em%3B%0Aline%2Dheight%3A%201%2E225%3B%0Aborder%2Dbottom%3A%201px%20solid%20%23eee%3B%0A%7D%0Ah2%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%3B%0A%7D%0Ah3%20%7B%0Afont%2Dsize%3A%201%2E5em%3B%0Aline%2Dheight%3A%201%2E43%3B%0A%7D%0Ah3%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E2%3B%0A%7D%0Ah4%20%7B%0Afont%2Dsize%3A%201%2E25em%3B%0A%7D%0Ah4%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E2%3B%0A%7D%0Ah5%20%7B%0Afont%2Dsize%3A%201em%3B%0A%7D%0Ah5%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E1%3B%0A%7D%0Ah6%20%7B%0Afont%2Dsize%3A%201em%3B%0Acolor%3A%20%23777%3B%0A%7D%0Ah6%20%2Eanchor%20%7B%0Aline%2Dheight%3A%201%2E1%3B%0A%7D%0Ap%2C%0Ablockquote%2C%0Aul%2C%0Aol%2C%0Adl%2C%0Atable%2C%0Apre%20%7B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%2016px%3B%0A%7D%0Ahr%20%7B%0Aheight%3A%204px%3B%0Apadding%3A%200%3B%0Amargin%3A%2016px%200%3B%0Abackground%2Dcolor%3A%20%23e7e7e7%3B%0Aborder%3A%200%20none%3B%0A%7D%0Aul%2C%0Aol%20%7B%0Apadding%2Dleft%3A%202em%3B%0A%7D%0Aul%20ul%2C%0Aul%20ol%2C%0Aol%20ol%2C%0Aol%20ul%20%7B%0Amargin%2Dtop%3A%200%3B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Ali%3Ep%20%7B%0Amargin%2Dtop%3A%2016px%3B%0A%7D%0Adl%20%7B%0Apadding%3A%200%3B%0A%7D%0Adl%20dt%20%7B%0Apadding%3A%200%3B%0Amargin%2Dtop%3A%2016px%3B%0Afont%2Dsize%3A%201em%3B%0Afont%2Dstyle%3A%20italic%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Adl%20dd%20%7B%0Apadding%3A%200%2016px%3B%0Amargin%2Dbottom%3A%2016px%3B%0A%7D%0Ablockquote%20%7B%0Apadding%3A%200%2015px%3B%0Acolor%3A%20%23777%3B%0Aborder%2Dleft%3A%204px%20solid%20%23ddd%3B%0A%7D%0Ablockquote%3E%3Afirst%2Dchild%20%7B%0Amargin%2Dtop%3A%200%3B%0A%7D%0Ablockquote%3E%3Alast%2Dchild%20%7B%0Amargin%2Dbottom%3A%200%3B%0A%7D%0Atable%20%7B%0Adisplay%3A%20block%3B%0Awidth%3A%20100%25%3B%0Aoverflow%3A%20auto%3B%0Aword%2Dbreak%3A%20normal%3B%0Aword%2Dbreak%3A%20keep%2Dall%3B%0A%7D%0Atable%20th%20%7B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0Atable%20th%2C%0Atable%20td%20%7B%0Apadding%3A%206px%2013px%3B%0Aborder%3A%201px%20solid%20%23ddd%3B%0A%7D%0Atable%20tr%20%7B%0Abackground%2Dcolor%3A%20%23fff%3B%0Aborder%2Dtop%3A%201px%20solid%20%23ccc%3B%0A%7D%0Atable%20tr%3Anth%2Dchild%282n%29%20%7B%0Abackground%2Dcolor%3A%20%23f8f8f8%3B%0A%7D%0Aimg%20%7B%0Amax%2Dwidth%3A%20100%25%3B%0Abox%2Dsizing%3A%20content%2Dbox%3B%0Abackground%2Dcolor%3A%20%23fff%3B%0A%7D%0Acode%20%7B%0Apadding%3A%200%3B%0Apadding%2Dtop%3A%200%2E2em%3B%0Apadding%2Dbottom%3A%200%2E2em%3B%0Amargin%3A%200%3B%0Afont%2Dsize%3A%2085%25%3B%0Abackground%2Dcolor%3A%20rgba%280%2C0%2C0%2C0%2E04%29%3B%0Aborder%2Dradius%3A%203px%3B%0A%7D%0Acode%3Abefore%2C%0Acode%3Aafter%20%7B%0Aletter%2Dspacing%3A%20%2D0%2E2em%3B%0Acontent%3A%20%22%5C00a0%22%3B%0A%7D%0Apre%3Ecode%20%7B%0Apadding%3A%200%3B%0Amargin%3A%200%3B%0Afont%2Dsize%3A%20100%25%3B%0Aword%2Dbreak%3A%20normal%3B%0Awhite%2Dspace%3A%20pre%3B%0Abackground%3A%20transparent%3B%0Aborder%3A%200%3B%0A%7D%0A%2Ehighlight%20%7B%0Amargin%2Dbottom%3A%2016px%3B%0A%7D%0A%2Ehighlight%20pre%2C%0Apre%20%7B%0Apadding%3A%2016px%3B%0Aoverflow%3A%20auto%3B%0Afont%2Dsize%3A%2085%25%3B%0Aline%2Dheight%3A%201%2E45%3B%0Abackground%2Dcolor%3A%20%23f7f7f7%3B%0Aborder%2Dradius%3A%203px%3B%0A%7D%0A%2Ehighlight%20pre%20%7B%0Amargin%2Dbottom%3A%200%3B%0Aword%2Dbreak%3A%20normal%3B%0A%7D%0Apre%20%7B%0Aword%2Dwrap%3A%20normal%3B%0A%7D%0Apre%20code%20%7B%0Adisplay%3A%20inline%3B%0Amax%2Dwidth%3A%20initial%3B%0Apadding%3A%200%3B%0Amargin%3A%200%3B%0Aoverflow%3A%20initial%3B%0Aline%2Dheight%3A%20inherit%3B%0Aword%2Dwrap%3A%20normal%3B%0Abackground%2Dcolor%3A%20transparent%3B%0Aborder%3A%200%3B%0A%7D%0Apre%20code%3Abefore%2C%0Apre%20code%3Aafter%20%7B%0Acontent%3A%20normal%3B%0A%7D%0Akbd%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0Apadding%3A%203px%205px%3B%0Afont%2Dsize%3A%2011px%3B%0Aline%2Dheight%3A%2010px%3B%0Acolor%3A%20%23555%3B%0Avertical%2Dalign%3A%20middle%3B%0Abackground%2Dcolor%3A%20%23fcfcfc%3B%0Aborder%3A%20solid%201px%20%23ccc%3B%0Aborder%2Dbottom%2Dcolor%3A%20%23bbb%3B%0Aborder%2Dradius%3A%203px%3B%0Abox%2Dshadow%3A%20inset%200%20%2D1px%200%20%23bbb%3B%0A%7D%0A%2Epl%2Dc%20%7B%0Acolor%3A%20%23969896%3B%0A%7D%0A%2Epl%2Dc1%2C%0A%2Epl%2Ds%20%2Epl%2Dv%20%7B%0Acolor%3A%20%230086b3%3B%0A%7D%0A%2Epl%2De%2C%0A%2Epl%2Den%20%7B%0Acolor%3A%20%23795da3%3B%0A%7D%0A%2Epl%2Ds%20%2Epl%2Ds1%2C%0A%2Epl%2Dsmi%20%7B%0Acolor%3A%20%23333%3B%0A%7D%0A%2Epl%2Dent%20%7B%0Acolor%3A%20%2363a35c%3B%0A%7D%0A%2Epl%2Dk%20%7B%0Acolor%3A%20%23a71d5d%3B%0A%7D%0A%2Epl%2Dpds%2C%0A%2Epl%2Ds%2C%0A%2Epl%2Ds%20%2Epl%2Dpse%20%2Epl%2Ds1%2C%0A%2Epl%2Dsr%2C%0A%2Epl%2Dsr%20%2Epl%2Dcce%2C%0A%2Epl%2Dsr%20%2Epl%2Dsra%2C%0A%2Epl%2Dsr%20%2Epl%2Dsre%20%7B%0Acolor%3A%20%23183691%3B%0A%7D%0A%2Epl%2Dv%20%7B%0Acolor%3A%20%23ed6a43%3B%0A%7D%0A%2Epl%2Did%20%7B%0Acolor%3A%20%23b52a1d%3B%0A%7D%0A%2Epl%2Dii%20%7B%0Abackground%2Dcolor%3A%20%23b52a1d%3B%0Acolor%3A%20%23f8f8f8%3B%0A%7D%0A%2Epl%2Dsr%20%2Epl%2Dcce%20%7B%0Acolor%3A%20%2363a35c%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dml%20%7B%0Acolor%3A%20%23693a17%3B%0A%7D%0A%2Epl%2Dmh%2C%0A%2Epl%2Dmh%20%2Epl%2Den%2C%0A%2Epl%2Dms%20%7B%0Acolor%3A%20%231d3e81%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dmq%20%7B%0Acolor%3A%20%23008080%3B%0A%7D%0A%2Epl%2Dmi%20%7B%0Acolor%3A%20%23333%3B%0Afont%2Dstyle%3A%20italic%3B%0A%7D%0A%2Epl%2Dmb%20%7B%0Acolor%3A%20%23333%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dmd%20%7B%0Abackground%2Dcolor%3A%20%23ffecec%3B%0Acolor%3A%20%23bd2c00%3B%0A%7D%0A%2Epl%2Dmi1%20%7B%0Abackground%2Dcolor%3A%20%23eaffea%3B%0Acolor%3A%20%2355a532%3B%0A%7D%0A%2Epl%2Dmdr%20%7B%0Acolor%3A%20%23795da3%3B%0Afont%2Dweight%3A%20bold%3B%0A%7D%0A%2Epl%2Dmo%20%7B%0Acolor%3A%20%231d3e81%3B%0A%7D%0Akbd%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0Apadding%3A%203px%205px%3B%0Afont%3A%2011px%20Consolas%2C%20%22Liberation%20Mono%22%2C%20Menlo%2C%20Courier%2C%20monospace%3B%0Aline%2Dheight%3A%2010px%3B%0Acolor%3A%20%23555%3B%0Avertical%2Dalign%3A%20middle%3B%0Abackground%2Dcolor%3A%20%23fcfcfc%3B%0Aborder%3A%20solid%201px%20%23ccc%3B%0Aborder%2Dbottom%2Dcolor%3A%20%23bbb%3B%0Aborder%2Dradius%3A%203px%3B%0Abox%2Dshadow%3A%20inset%200%20%2D1px%200%20%23bbb%3B%0A%7D%0A%2Etask%2Dlist%2Ditem%20%7B%0Alist%2Dstyle%2Dtype%3A%20none%3B%0A%7D%0A%2Etask%2Dlist%2Ditem%2B%2Etask%2Dlist%2Ditem%20%7B%0Amargin%2Dtop%3A%203px%3B%0A%7D%0A%2Etask%2Dlist%2Ditem%20input%20%7B%0Amargin%3A%200%200%2E35em%200%2E25em%20%2D1%2E6em%3B%0Avertical%2Dalign%3A%20middle%3B%0A%7D%0A%3Achecked%2B%2Eradio%2Dlabel%20%7B%0Az%2Dindex%3A%201%3B%0Aposition%3A%20relative%3B%0Aborder%2Dcolor%3A%20%234078c0%3B%0A%7D%0A%2EsourceLine%20%7B%0Adisplay%3A%20inline%2Dblock%3B%0A%7D%0Acode%20%2Ekw%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Edt%20%7B%20color%3A%20%23ed6a43%3B%20%7D%0Acode%20%2Edv%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Ebn%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Efl%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Ech%20%7B%20color%3A%20%23009999%3B%20%7D%0Acode%20%2Est%20%7B%20color%3A%20%23183691%3B%20%7D%0Acode%20%2Eco%20%7B%20color%3A%20%23969896%3B%20%7D%0Acode%20%2Eot%20%7B%20color%3A%20%230086b3%3B%20%7D%0Acode%20%2Eal%20%7B%20color%3A%20%23a61717%3B%20%7D%0Acode%20%2Efu%20%7B%20color%3A%20%2363a35c%3B%20%7D%0Acode%20%2Eer%20%7B%20color%3A%20%23a61717%3B%20background%2Dcolor%3A%20%23e3d2d2%3B%20%7D%0Acode%20%2Ewa%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Ecn%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Esc%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Evs%20%7B%20color%3A%20%23183691%3B%20%7D%0Acode%20%2Ess%20%7B%20color%3A%20%23183691%3B%20%7D%0Acode%20%2Eim%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Eva%20%7Bcolor%3A%20%23008080%3B%20%7D%0Acode%20%2Ecf%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Eop%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Ebu%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Eex%20%7B%20color%3A%20%23000000%3B%20%7D%0Acode%20%2Epp%20%7B%20color%3A%20%23999999%3B%20%7D%0Acode%20%2Eat%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Edo%20%7B%20color%3A%20%23969896%3B%20%7D%0Acode%20%2Ean%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Ecv%20%7B%20color%3A%20%23008080%3B%20%7D%0Acode%20%2Ein%20%7B%20color%3A%20%23008080%3B%20%7D%0A" rel="stylesheet">
<style>
body {
  box-sizing: border-box;
  min-width: 200px;
  max-width: 980px;
  margin: 0 auto;
  padding: 45px;
  padding-top: 0px;
}
</style>

</head>

<body>

<h1 id="experiment-1-semantic-competition">Experiment 1 (Semantic Competition)</h1>
<p>Williams, G.P., Kukona, A., &amp; Kamide, Y.</p>
<p>This document provides a reproducible analysis for Experiment 1 of the paper <em>Spatial narrative context modulates semantic (but not visual) competition during discourse processing</em> by Glenn P. Williams, Anuenue Kukona, &amp; Yuki Kamide.</p>
<h1 id="options-packages-functions-and-data">Options, Packages, Functions, and Data</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">1</span>, <span class="dt">digits =</span> <span class="dv">3</span>)
<span class="kw">load</span>(<span class="kw">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;semantic_data.Rdata&quot;</span>))
semantic_demo &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="kw">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;semantic_demographics.csv&quot;</span>))</code></pre></div>
<h1 id="sample-demographics">Sample Demographics</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># gender count</span>
semantic_gender_n &lt;-<span class="st"> </span>semantic_demo <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(included <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(gender) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ungroup</span>()

<span class="co"># age averages</span>
semantic_ages &lt;-<span class="st"> </span>semantic_demo <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(included <span class="op">==</span><span class="st"> &quot;yes&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(
    <span class="dt">min_age =</span> <span class="kw">min</span>(age),
    <span class="dt">max_age =</span> <span class="kw">max</span>(age),
    <span class="dt">mean_age =</span> <span class="kw">mean</span>(age),
    <span class="dt">sd_age =</span> <span class="kw">sd</span>(age)
  )</code></pre></div>
<p>60 (11 male) native speakers of English from the University of Dundee community (aged 17- 33, <em>M</em> = 20.617, <em>SD</em> = 3.664) took part in this study for partial course credit. All participants had uncorrected vision, wore soft contact lenses, or wore spectacles, and had no known auditory, visual, or language disorders.</p>
<h1 id="data-preparation">Data Preparation</h1>
<p>We subsetted the data to the time window of the critical noun (e.g. &quot;piano&quot;) + 300ms to allow for eye-movements to be driven by semantic competition. Within this time window, we further subsetted our data to fixations on the competitor and the average fixations on the two distractors (henceforth, distractor).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define time window</span>
t_window &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;crit_noun_on&quot;</span>, <span class="st">&quot;crit_noun_off&quot;</span>)

<span class="co"># shift window by how much?</span>
window_shift &lt;-<span class="st"> </span><span class="dv">300</span>

<span class="co"># reset interest area labels for later subsetting</span>
ias &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;c&quot;</span>, <span class="st">&quot;d&quot;</span>)

<span class="co"># establish conditions for later summaries</span>
conds &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;IA2&quot;</span>)

<span class="co"># define variables for centering</span>
centering_list &lt;-<span class="st"> </span><span class="kw">list</span>(
  <span class="dt">factors =</span> <span class="kw">c</span>(<span class="st">&quot;condition&quot;</span>, <span class="st">&quot;IA2&quot;</span>),
  <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;together&quot;</span>, <span class="st">&quot;c&quot;</span>)
)

<span class="co"># tidy data before analysis (make distractor looks the average across the two)</span>
tidy_data &lt;-<span class="st"> </span>semantic_data <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(
    <span class="dt">item =</span> <span class="kw">as.factor</span>(item),
    <span class="dt">d =</span> (d1 <span class="op">+</span><span class="st"> </span>d2) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>,
    <span class="dt">time_0 =</span> time <span class="op">-</span><span class="st"> </span><span class="kw">UQ</span>(<span class="kw">as.name</span>(t_window[<span class="dv">1</span>]))
  ) <span class="op">%&gt;%</span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(t, d1, d2))

<span class="co"># subset data to time window</span>
sub_data &lt;-<span class="st"> </span><span class="kw">subset_to_window</span>(tidy_data, <span class="st">&quot;time_0&quot;</span>, timeM, t_window, window_shift)
long_data &lt;-<span class="st"> </span><span class="kw">make_data_long</span>(sub_data, <span class="st">&quot;IA2&quot;</span>, ias, <span class="st">&quot;fix&quot;</span>)</code></pre></div>
<h1 id="data-aggregation">Data Aggregation</h1>
<p>Prior to running our analyses, we aggregated the data first by subjects, and then by items, across the entire time window. This aggregation was conducted in order to account for a heavy bias in fixation probabilities within trials for each subject, whereby within subjects and items several trials could consist of 0% or 100% looking towards one interest area. Additionally, models fitted to the subject-by-item data violated the assumption of homoscedasticity for residuals.</p>
<p>Additionally, we transformed our dependent variable, the proportion of fixations on a given interest area, into arcsin square root transformed proportions. This transformation attempts to account for the bounded nature of the underlying binomial response data that makes up a proportion. This transformation was used to account for the lack of homogeneity in the variance across the range of possible outcomes, with a larger variance towards the endpoints (i.e. 0 or 1) (Mirman, 2014).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># aggregate data by subjects, center variables, and make new dvs</span>
by_subj &lt;-<span class="st"> </span><span class="kw">aggregate_data</span>(long_data, <span class="st">&quot;subject&quot;</span>, conds, <span class="st">&quot;fix&quot;</span>)
by_subj &lt;-<span class="st"> </span><span class="kw">centre_many</span>(by_subj, centering_list)
by_subj &lt;-<span class="st"> </span><span class="kw">make_dvs</span>(by_subj, <span class="st">&quot;y&quot;</span>, <span class="st">&quot;N&quot;</span>)

<span class="co"># aggregate data by items, center variables, and make new dvs</span>
by_items &lt;-<span class="st"> </span><span class="kw">aggregate_data</span>(long_data, <span class="st">&quot;item&quot;</span>, conds, <span class="st">&quot;fix&quot;</span>)
by_items &lt;-<span class="st"> </span><span class="kw">centre_many</span>(by_items, centering_list)
by_items &lt;-<span class="st"> </span><span class="kw">make_dvs</span>(by_items, <span class="st">&quot;y&quot;</span>, <span class="st">&quot;N&quot;</span>)</code></pre></div>
<h1 id="model-structure">Model Structure</h1>
<p>We conducted one main analysis which looked at the main effects and interactions between the condition and interest area variables. To perform this analysis, we used a hierarchical mixed-effects model with an arcsin squareroot transformation. Our models contained fixed effects of condition and interest area (centred) and their interaction. Additionally, our random effects structure took the form of random intercepts by subjects/items, and random intercepts of subjects/items nested within condition, and subjects/items nested within interest area.</p>
<p>Where interactions between our fixed effects were present, we conducted pairwise comparisons to explore the simple effects of each fixed effect.</p>
<p>To explore the main effect of condition within each interest area, we first subsetted our data to each interest area before submitting the data to a hierarchical mixed effects model with a fixed effect of condition, and random intercepts by subjects/items.</p>
<p>We used a similar procedure to explore the fixed effect of interest area within each condition, but this time subsetting our data to each condition, and fitting models with a fixed effect of interest area, and random intercepts by subjects/items.</p>
<p>In all models, we used the maximal converging random effects structure (Barr et al., 2013). For follow-up tests, all p-values are reported using the Bonferroni correction.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define model details ----</span>

<span class="co"># main_model_formula</span>
main_formula &lt;-<span class="st"> </span><span class="kw">as.formula</span>(
  <span class="st">&quot;asin ~ condition_c * IA2_c + </span>
<span class="st">  (1 | by) + (1 | by: condition_c) + (1 | by: IA2_c)&quot;</span>
)

<span class="co"># condition by IA formula, IA by condition formula</span>
cond_by_IA_formula &lt;-<span class="st"> </span><span class="kw">as.formula</span>(<span class="st">&quot;asin ~ condition + (1 | by)&quot;</span>)
IA_by_cond_formula &lt;-<span class="st"> </span><span class="kw">as.formula</span>(<span class="st">&quot;asin ~ IA2 + (1 | by)&quot;</span>)

<span class="co"># define number of comparisons for p-value correction</span>
n_comparisons &lt;-<span class="st"> </span><span class="dv">4</span>

<span class="co"># by-subjects ----</span>

<span class="co"># interaction model: testing for main effects and interactions</span>
by_subj_model &lt;-<span class="st"> </span><span class="kw">tidy_model</span>(<span class="kw">lmer</span>(main_formula, <span class="dt">data =</span> by_subj))

<span class="co"># analyse condition split by IA, then adjust p-values</span>
by_subj_cond_IA &lt;-<span class="st"> </span><span class="kw">test_interactions</span>(by_subj, IA2, cond_by_IA_formula)
by_subj_cond_IA<span class="op">$</span>p_value &lt;-<span class="st"> </span><span class="kw">adjust_multiple</span>(by_subj_cond_IA, n_comparisons)

<span class="co"># analyse effect of interest area split by condition, then adjust p-values</span>
by_subj_IA_cond &lt;-<span class="st"> </span><span class="kw">test_interactions</span>(by_subj, condition, IA_by_cond_formula)
by_subj_IA_cond<span class="op">$</span>p_value &lt;-<span class="st"> </span><span class="kw">adjust_multiple</span>(by_subj_IA_cond, n_comparisons)

<span class="co"># by-items ----</span>

<span class="co"># interaction model: testing for main effects and interactions</span>
by_items_model &lt;-<span class="st"> </span><span class="kw">tidy_model</span>(<span class="kw">lmer</span>(main_formula, <span class="dt">data =</span> by_items))

<span class="co"># analyse condition split by IA, then adjust p-values</span>
by_items_cond_IA &lt;-<span class="st"> </span><span class="kw">test_interactions</span>(by_items, IA2, cond_by_IA_formula)
by_items_cond_IA<span class="op">$</span>p_value &lt;-<span class="st"> </span><span class="kw">adjust_multiple</span>(by_items_cond_IA, n_comparisons)

<span class="co"># analyse effect of interest area split by condition, then adjust p-values</span>
by_items_IA_cond &lt;-<span class="st"> </span><span class="kw">test_interactions</span>(by_items, condition, IA_by_cond_formula)
by_items_IA_cond<span class="op">$</span>p_value &lt;-<span class="st"> </span><span class="kw">adjust_multiple</span>(by_items_IA_cond, n_comparisons)</code></pre></div>
<h1 id="descriptive-statistics">Descriptive Statistics</h1>
<p>Below, we show a table of the means, standard deviations, and confidence intervals for the proportion of fixations and arcsin squareroot transformed fixations on each interest area within each condition aggregated by subjects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># descriptives</span>
descriptives_table &lt;-<span class="st"> </span>by_subj <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(IA2, condition) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(
    <span class="dt">n =</span> <span class="kw">length</span>(<span class="kw">unique</span>(by)),
    <span class="dt">prop_mean =</span> <span class="kw">mean</span>(prop),
    <span class="dt">prop_sd =</span> <span class="kw">sd</span>(prop),
    <span class="dt">prop_ci =</span> <span class="kw">ci_of_mean</span>(prop_mean, prop_sd, n),
    <span class="dt">asin_mean =</span> <span class="kw">mean</span>(asin),
    <span class="dt">asin_sd =</span> <span class="kw">sd</span>(asin),
    <span class="dt">asin_ci =</span> <span class="kw">ci_of_mean</span>(asin_mean, asin_sd, n)
    ) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>n)

<span class="co"># print output</span>
descriptives_table <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">IA2</th>
<th align="left">condition</th>
<th align="right">prop_mean</th>
<th align="right">prop_sd</th>
<th align="left">prop_ci</th>
<th align="right">asin_mean</th>
<th align="right">asin_sd</th>
<th align="left">asin_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">c</td>
<td align="left">apart</td>
<td align="right">0.150</td>
<td align="right">0.072</td>
<td align="left">[0.131; 0.169]</td>
<td align="right">0.386</td>
<td align="right">0.109</td>
<td align="left">[0.358; 0.414]</td>
</tr>
<tr class="even">
<td align="left">c</td>
<td align="left">together</td>
<td align="right">0.201</td>
<td align="right">0.093</td>
<td align="left">[0.177; 0.225]</td>
<td align="right">0.451</td>
<td align="right">0.131</td>
<td align="left">[0.417; 0.485]</td>
</tr>
<tr class="odd">
<td align="left">d</td>
<td align="left">apart</td>
<td align="right">0.153</td>
<td align="right">0.054</td>
<td align="left">[0.139; 0.167]</td>
<td align="right">0.396</td>
<td align="right">0.078</td>
<td align="left">[0.376; 0.416]</td>
</tr>
<tr class="even">
<td align="left">d</td>
<td align="left">together</td>
<td align="right">0.149</td>
<td align="right">0.055</td>
<td align="left">[0.135; 0.163]</td>
<td align="right">0.389</td>
<td align="right">0.081</td>
<td align="left">[0.368; 0.410]</td>
</tr>
</tbody>
</table>
<h1 id="interaction-model">Interaction Model</h1>
<p>For both by-subjects and by-items analyses, we found a significant interaction between condition and interest area. As such, we performed follow-up tests to explore the direction of effect.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">merge_tables</span>(by_subj_model, by_items_model) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">pretty_confint</span>(., <span class="st">&quot;2.5 %&quot;</span>, <span class="st">&quot;97.5 %&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">aggregate</th>
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p_value</th>
<th align="left">ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Subjects</td>
<td align="left">(Intercept)</td>
<td align="right">0.406</td>
<td align="right">0.007</td>
<td align="right">56.24</td>
<td align="right">0.000</td>
<td align="left">[0.391; 0.420]</td>
</tr>
<tr class="even">
<td align="left">Subjects</td>
<td align="left">condition_c</td>
<td align="right">0.029</td>
<td align="right">0.013</td>
<td align="right">2.28</td>
<td align="right">0.023</td>
<td align="left">[0.004; 0.054]</td>
</tr>
<tr class="odd">
<td align="left">Subjects</td>
<td align="left">condition_c:IA2_c</td>
<td align="right">0.072</td>
<td align="right">0.025</td>
<td align="right">2.83</td>
<td align="right">0.005</td>
<td align="left">[0.022; 0.122]</td>
</tr>
<tr class="even">
<td align="left">Subjects</td>
<td align="left">IA2_c</td>
<td align="right">0.025</td>
<td align="right">0.013</td>
<td align="right">1.99</td>
<td align="right">0.047</td>
<td align="left">[0.000; 0.050]</td>
</tr>
<tr class="odd">
<td align="left">Items</td>
<td align="left">(Intercept)</td>
<td align="right">0.409</td>
<td align="right">0.009</td>
<td align="right">45.38</td>
<td align="right">0.000</td>
<td align="left">[0.392; 0.427]</td>
</tr>
<tr class="even">
<td align="left">Items</td>
<td align="left">condition_c</td>
<td align="right">0.030</td>
<td align="right">0.010</td>
<td align="right">3.01</td>
<td align="right">0.003</td>
<td align="left">[0.010; 0.049]</td>
</tr>
<tr class="odd">
<td align="left">Items</td>
<td align="left">condition_c:IA2_c</td>
<td align="right">0.073</td>
<td align="right">0.020</td>
<td align="right">3.73</td>
<td align="right">0.000</td>
<td align="left">[0.035; 0.112]</td>
</tr>
<tr class="even">
<td align="left">Items</td>
<td align="left">IA2_c</td>
<td align="right">0.029</td>
<td align="right">0.018</td>
<td align="right">1.61</td>
<td align="right">0.107</td>
<td align="left">[-0.006; 0.064]</td>
</tr>
</tbody>
</table>
<h1 id="pairwise-comparisons">Pairwise Comparisons</h1>
<h2 id="condition-by-interest-area">Condition by Interest Area</h2>
<p>In both by-subjects and by-items analyses we found a significant difference between the two conditions (Together and Apart) on the (transformed) proportion of fixations on the competitor, with a larger proportion of fixations on the competitor in the Together (Mean = 0.201) condition than the Apart condition (Mean = 0.15). We found no significant difference between the Together (Mean = 0.149) and Apart (Mean = 0.153) conditions on the transformed proportion of fixations on the distractor.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">merge_tables</span>(by_subj_cond_IA, by_items_cond_IA) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">pretty_confint</span>(., <span class="st">&quot;2.5 %&quot;</span>, <span class="st">&quot;97.5 %&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">aggregate</th>
<th align="left">IA2</th>
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="left">p_value</th>
<th align="left">ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Subjects</td>
<td align="left">c</td>
<td align="left">(Intercept)</td>
<td align="right">0.386</td>
<td align="right">0.016</td>
<td align="right">24.830</td>
<td align="left">0.000</td>
<td align="left">[0.355; 0.416]</td>
</tr>
<tr class="even">
<td align="left">Subjects</td>
<td align="left">c</td>
<td align="left">conditiontogether</td>
<td align="right">0.065</td>
<td align="right">0.022</td>
<td align="right">2.957</td>
<td align="left">0.012</td>
<td align="left">[0.022; 0.108]</td>
</tr>
<tr class="odd">
<td align="left">Subjects</td>
<td align="left">d</td>
<td align="left">(Intercept)</td>
<td align="right">0.396</td>
<td align="right">0.010</td>
<td align="right">38.569</td>
<td align="left">0.000</td>
<td align="left">[0.376; 0.417]</td>
</tr>
<tr class="even">
<td align="left">Subjects</td>
<td align="left">d</td>
<td align="left">conditiontogether</td>
<td align="right">-0.007</td>
<td align="right">0.013</td>
<td align="right">-0.552</td>
<td align="left">1.000</td>
<td align="left">[-0.032; 0.018]</td>
</tr>
<tr class="odd">
<td align="left">Items</td>
<td align="left">c</td>
<td align="left">(Intercept)</td>
<td align="right">0.391</td>
<td align="right">0.017</td>
<td align="right">23.433</td>
<td align="left">0.000</td>
<td align="left">[0.358; 0.423]</td>
</tr>
<tr class="even">
<td align="left">Items</td>
<td align="left">c</td>
<td align="left">conditiontogether</td>
<td align="right">0.066</td>
<td align="right">0.017</td>
<td align="right">3.828</td>
<td align="left">0.000</td>
<td align="left">[0.032; 0.100]</td>
</tr>
<tr class="odd">
<td align="left">Items</td>
<td align="left">d</td>
<td align="left">(Intercept)</td>
<td align="right">0.398</td>
<td align="right">0.012</td>
<td align="right">33.159</td>
<td align="left">0.000</td>
<td align="left">[0.375; 0.422]</td>
</tr>
<tr class="even">
<td align="left">Items</td>
<td align="left">d</td>
<td align="left">conditiontogether</td>
<td align="right">-0.007</td>
<td align="right">0.009</td>
<td align="right">-0.757</td>
<td align="left">1.000</td>
<td align="left">[-0.025; 0.011]</td>
</tr>
</tbody>
</table>
<h2 id="interest-area-by-condition">Interest Area by Condition</h2>
<p>In both by-subjects and by-items analyses we found a significant difference between the (transformed) proportion of fixations on the two interest areas (Competitor and Distractor) in the Together condition only. Here, we found a larger proportion of fixations on the competitor (Mean = 0.201) than the distractor (Mean = 0.149). In the Apart condition, we found no significant difference between the proportions of fixations on the competitor (Mean = 0.15) and distractor (Mean = 0.153).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">merge_tables</span>(by_subj_IA_cond, by_items_IA_cond) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">pretty_confint</span>(., <span class="st">&quot;2.5 %&quot;</span>, <span class="st">&quot;97.5 %&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">aggregate</th>
<th align="left">condition</th>
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="left">p_value</th>
<th align="left">ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Subjects</td>
<td align="left">apart</td>
<td align="left">(Intercept)</td>
<td align="right">0.386</td>
<td align="right">0.012</td>
<td align="right">31.606</td>
<td align="left">0.000</td>
<td align="left">[0.362; 0.410]</td>
</tr>
<tr class="even">
<td align="left">Subjects</td>
<td align="left">apart</td>
<td align="left">IA2d</td>
<td align="right">0.011</td>
<td align="right">0.017</td>
<td align="right">0.616</td>
<td align="left">1.000</td>
<td align="left">[-0.023; 0.044]</td>
</tr>
<tr class="odd">
<td align="left">Subjects</td>
<td align="left">together</td>
<td align="left">(Intercept)</td>
<td align="right">0.451</td>
<td align="right">0.014</td>
<td align="right">32.030</td>
<td align="left">0.000</td>
<td align="left">[0.423; 0.478]</td>
</tr>
<tr class="even">
<td align="left">Subjects</td>
<td align="left">together</td>
<td align="left">IA2d</td>
<td align="right">-0.061</td>
<td align="right">0.020</td>
<td align="right">-3.080</td>
<td align="left">0.008</td>
<td align="left">[-0.100; -0.022]</td>
</tr>
<tr class="odd">
<td align="left">Items</td>
<td align="left">apart</td>
<td align="left">(Intercept)</td>
<td align="right">0.391</td>
<td align="right">0.013</td>
<td align="right">29.327</td>
<td align="left">0.000</td>
<td align="left">[0.365; 0.417]</td>
</tr>
<tr class="even">
<td align="left">Items</td>
<td align="left">apart</td>
<td align="left">IA2d</td>
<td align="right">0.008</td>
<td align="right">0.019</td>
<td align="right">0.405</td>
<td align="left">1.000</td>
<td align="left">[-0.029; 0.045]</td>
</tr>
<tr class="odd">
<td align="left">Items</td>
<td align="left">together</td>
<td align="left">(Intercept)</td>
<td align="right">0.457</td>
<td align="right">0.016</td>
<td align="right">29.208</td>
<td align="left">0.000</td>
<td align="left">[0.426; 0.488]</td>
</tr>
<tr class="even">
<td align="left">Items</td>
<td align="left">together</td>
<td align="left">IA2d</td>
<td align="right">-0.066</td>
<td align="right">0.022</td>
<td align="right">-2.971</td>
<td align="left">0.012</td>
<td align="left">[-0.109; -0.022]</td>
</tr>
</tbody>
</table>
<h1 id="evaluating-evidence-for-the-null-hypothesis">Evaluating Evidence for the Null Hypothesis</h1>
<p>The effect of condition had a non-significant effect of fixations to the distractor across conditions. Moreover, the effect of interest area had a non-significant effect on fixations in the Apart condition. However, we cannot take this as evidence of the absence of any effect in these cases. One way to evaluate support for the null hypothesis is through using Bayes Factors. Here, we use the Bayesian Information Criterion (BIC) approximation to the Bayes factor, which affords easy computation using the same model specifications in lme4 used to evaluate support for the alternative hypothesis under the NHST procedure. A discussion of how to compute this approximation, as well as the strengths and weaknesses of this method are outlined in Wagenmakers (2007).</p>
<h2 id="the-effect-of-condition-on-the-distractor">The Effect of Condition on the Distractor</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># by-subjects (evaluate alternative against null - H01)</span>
cond_dist_subj_max &lt;-<span class="st"> </span><span class="kw">lmer</span>(
  cond_by_IA_formula,
  <span class="dt">data =</span> by_subj <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(IA2 <span class="op">==</span><span class="st"> &quot;d&quot;</span>),
  <span class="dt">REML =</span> F
)
cond_dist_subj_min &lt;-<span class="st"> </span><span class="kw">update</span>(cond_dist_subj_max, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>condition)

<span class="co"># BF_01</span>
cond_dist_bf_subj &lt;-<span class="st"> </span><span class="kw">exp</span>((<span class="kw">BIC</span>(cond_dist_subj_max) <span class="op">-</span><span class="st"> </span><span class="kw">BIC</span>(cond_dist_subj_min)) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)

<span class="co"># by-items</span>
cond_dist_items_max &lt;-<span class="st"> </span><span class="kw">lmer</span>(
  cond_by_IA_formula,
  <span class="dt">data =</span> by_items <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(IA2 <span class="op">==</span><span class="st"> &quot;d&quot;</span>),
  <span class="dt">REML =</span> F
)

cond_dist_items_min &lt;-<span class="st"> </span><span class="kw">update</span>(cond_dist_items_max, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>condition)

<span class="co"># BF_01</span>
cond_dist_bf_items &lt;-<span class="st"> </span><span class="kw">exp</span>((<span class="kw">BIC</span>(cond_dist_items_max) <span class="op">-</span><span class="st"> </span><span class="kw">BIC</span>(cond_dist_items_min)) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)</code></pre></div>
<p>The BIC approximation to the Bayes Factor shows that the the data are more likely under the null than the alternative hypothesis for both by-subjects and by-items analyses (by-subjects: <em>BIC(H<sub>0</sub>)</em> = -257.899 <em>BIC(H<sub>1</sub>)</em> = -253.42, <em>BF<sub>01</sub></em> ≈ 9.388; by-items: <em>BIC(H<sub>0</sub>)</em> = -172.803 <em>BIC(H<sub>1</sub>)</em> = -169.231, <em>BF<sub>01</sub></em> ≈ 5.967). This suggests that fixations on the distractor are not influenced by the discourse condition.</p>
<h2 id="the-effect-of-interest-area-in-the-apart-condition">The Effect of Interest Area in the Apart condition</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># by-subjects (evaluate alternative against null - H01)</span>
ia_apart_subj_max &lt;-<span class="st"> </span><span class="kw">lmer</span>(
  IA_by_cond_formula,
  <span class="dt">data =</span> by_subj <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(condition <span class="op">==</span><span class="st"> &quot;apart&quot;</span>),
  <span class="dt">REML =</span> F
)
ia_apart_subj_min &lt;-<span class="st"> </span><span class="kw">update</span>(ia_apart_subj_max, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>IA2)

<span class="co"># BF_01</span>
ia_apart_bf_subj &lt;-<span class="st"> </span><span class="kw">exp</span>((<span class="kw">BIC</span>(ia_apart_subj_max) <span class="op">-</span><span class="st"> </span><span class="kw">BIC</span>(ia_apart_subj_min)) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)

<span class="co"># by-items</span>
ia_apart_items_max &lt;-<span class="st"> </span><span class="kw">lmer</span>(
  IA_by_cond_formula,
  <span class="dt">data =</span> by_items <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(condition <span class="op">==</span><span class="st"> &quot;apart&quot;</span>),
  <span class="dt">REML =</span> F
)
ia_apart_items_min &lt;-<span class="st"> </span><span class="kw">update</span>(ia_apart_items_max, . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span>IA2)

<span class="co"># BF_01</span>
ia_apart_bf_items &lt;-<span class="st"> </span><span class="kw">exp</span>((<span class="kw">BIC</span>(ia_apart_items_max) <span class="op">-</span><span class="st"> </span><span class="kw">BIC</span>(ia_apart_items_min)) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)</code></pre></div>
<p>The BIC approximation to the Bayes Factor shows that the the data are more likely under the null than the alternative hypothesis for both by-subjects and by-items analyses (by-subjects: <em>BIC(H<sub>0</sub>)</em> = -212.838, <em>BIC(H<sub>1</sub>)</em> = -208.436, <em>BF<sub>01</sub></em> ≈ 9.035; by-items: <em>BIC(H<sub>0</sub>)</em> = -138.69, <em>BIC(H<sub>1</sub>)</em> = -134.7, <em>BF<sub>01</sub></em> ≈ 7.352). This suggests that there is no difference in the fixations on the competitor and distractor in the Apart condition.</p>
<h1 id="references">References</h1>
<p>Barr, D. J., Levy, R., Scheepers, C., &amp; Tily, H. J. (2013). Random effects structure for confirmatory hypothesis testing: Keep it maximal. <em>Journal of Memory and Language, 68</em>(3), 255-278. <a href="https://doi.org/10.1016/j.jml.2012.11.001" class="uri">https://doi.org/10.1016/j.jml.2012.11.001</a></p>
<p>Mirman, D. (2014). <em>Growth Curve Analysis and Visualization Using R</em>. Boca Ranton, FL.: Chapman and Hall/CRC Press.</p>
<p>Wagenmakers, E.-J. (2007). A practical solution to the pervasive problems of p values. <em>Psychonomic Bulletin &amp; Review, 14</em>(5), 779-804. <a href="https://doi.org/10.3758/BF03194105" class="uri">https://doi.org/10.3758/BF03194105</a></p>
<h1 id="session-information">Session Information</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">devtools<span class="op">::</span><span class="kw">session_info</span>()</code></pre></div>
<pre><code>## Session info -------------------------------------------------------------

##  setting  value                       
##  version  R version 3.5.1 (2018-07-02)
##  system   x86_64, mingw32             
##  ui       RStudio (1.1.414)           
##  language (EN)                        
##  collate  English_United Kingdom.1252 
##  tz       Europe/London               
##  date     2019-01-08

## Packages -----------------------------------------------------------------

##  package    * version  date       source        
##  assertthat   0.2.0    2017-04-11 CRAN (R 3.5.1)
##  backports    1.1.2    2017-12-13 CRAN (R 3.5.0)
##  base       * 3.5.1    2018-07-02 local         
##  bindr        0.1.1    2018-03-13 CRAN (R 3.5.1)
##  bindrcpp   * 0.2.2    2018-03-29 CRAN (R 3.5.1)
##  broom      * 0.5.0    2018-07-17 CRAN (R 3.5.1)
##  cli          1.0.0    2017-11-05 CRAN (R 3.5.1)
##  codetools    0.2-15   2016-10-05 CRAN (R 3.5.1)
##  colorspace   1.3-2    2016-12-14 CRAN (R 3.5.1)
##  compiler     3.5.1    2018-07-02 local         
##  crayon       1.3.4    2017-09-16 CRAN (R 3.5.1)
##  datasets   * 3.5.1    2018-07-02 local         
##  devtools     1.13.6   2018-06-27 CRAN (R 3.5.1)
##  digest       0.6.16   2018-08-22 CRAN (R 3.5.1)
##  dplyr      * 0.7.7    2018-10-16 CRAN (R 3.5.1)
##  evaluate     0.11     2018-07-17 CRAN (R 3.5.1)
##  fansi        0.3.0    2018-08-13 CRAN (R 3.5.1)
##  ggplot2    * 3.0.0    2018-07-03 CRAN (R 3.5.1)
##  glue         1.3.0    2018-07-17 CRAN (R 3.5.1)
##  graphics   * 3.5.1    2018-07-02 local         
##  grDevices  * 3.5.1    2018-07-02 local         
##  grid         3.5.1    2018-07-02 local         
##  gtable       0.2.0    2016-02-26 CRAN (R 3.5.1)
##  here       * 0.1      2017-05-28 CRAN (R 3.5.1)
##  highr        0.7      2018-06-09 CRAN (R 3.5.1)
##  htmltools    0.3.6    2017-04-28 CRAN (R 3.5.1)
##  knitr      * 1.20     2018-02-20 CRAN (R 3.5.1)
##  lattice      0.20-35  2017-03-25 CRAN (R 3.5.1)
##  lazyeval     0.2.1    2017-10-29 CRAN (R 3.5.1)
##  lme4       * 1.1-18-1 2018-08-17 CRAN (R 3.5.1)
##  magrittr     1.5      2014-11-22 CRAN (R 3.5.1)
##  MASS       * 7.3-50   2018-04-30 CRAN (R 3.5.1)
##  Matrix     * 1.2-14   2018-04-13 CRAN (R 3.5.1)
##  memoise      1.1.0    2017-04-21 CRAN (R 3.5.1)
##  methods    * 3.5.1    2018-07-02 local         
##  minqa        1.2.4    2014-10-09 CRAN (R 3.5.1)
##  multcomp   * 1.4-8    2017-11-08 CRAN (R 3.5.1)
##  munsell      0.5.0    2018-06-12 CRAN (R 3.5.1)
##  mvtnorm    * 1.0-8    2018-05-31 CRAN (R 3.5.0)
##  nlme         3.1-137  2018-04-07 CRAN (R 3.5.1)
##  nloptr       1.0.4    2017-08-22 CRAN (R 3.5.1)
##  pillar       1.3.0    2018-07-14 CRAN (R 3.5.1)
##  pkgconfig    2.0.2    2018-08-16 CRAN (R 3.5.1)
##  plyr         1.8.4    2016-06-08 CRAN (R 3.5.1)
##  purrr        0.2.5    2018-05-29 CRAN (R 3.5.1)
##  R6           2.2.2    2017-06-17 CRAN (R 3.5.1)
##  Rcpp         0.12.18  2018-07-23 CRAN (R 3.5.1)
##  rlang        0.3.0    2018-10-22 CRAN (R 3.5.1)
##  rmarkdown  * 1.10     2018-06-11 CRAN (R 3.5.1)
##  rprojroot    1.3-2    2018-01-03 CRAN (R 3.5.1)
##  rstudioapi   0.7      2017-09-07 CRAN (R 3.5.1)
##  sandwich     2.5-0    2018-08-17 CRAN (R 3.5.1)
##  scales       1.0.0    2018-08-09 CRAN (R 3.5.1)
##  splines      3.5.1    2018-07-02 local         
##  stats      * 3.5.1    2018-07-02 local         
##  stringi      1.1.7    2018-03-12 CRAN (R 3.5.0)
##  stringr    * 1.3.1    2018-05-10 CRAN (R 3.5.1)
##  survival   * 2.42-3   2018-04-16 CRAN (R 3.5.1)
##  TH.data    * 1.0-9    2018-07-10 CRAN (R 3.5.1)
##  tibble       1.4.2    2018-01-22 CRAN (R 3.5.1)
##  tidyr      * 0.8.1    2018-05-18 CRAN (R 3.5.1)
##  tidyselect   0.2.4    2018-02-26 CRAN (R 3.5.1)
##  tools        3.5.1    2018-07-02 local         
##  utf8         1.1.4    2018-05-24 CRAN (R 3.5.1)
##  utils      * 3.5.1    2018-07-02 local         
##  withr        2.1.2    2018-03-15 CRAN (R 3.5.1)
##  yaml         2.2.0    2018-07-25 CRAN (R 3.5.1)
##  zoo          1.8-3    2018-07-16 CRAN (R 3.5.1)</code></pre>

</body>
</html>
